### PR TITLE
Removed dead links

### PR DESCRIPTION
**Pull request by eddef**

### CODE REVIEW

**Comment by jtimon** [comment]
Sorry for taking so long to look at this, and thanks.
Maybe we can link to here for the wiki?

https://github.com/freicoin/freicoin/wiki

**Comment by eddef** [comment]
Yes,  that would be OK to start build on.

**Comment by jtimon** [comment]
Yes, there's only 3 articles but still...
Ok, so will you please update the PR so that I can merge it?

**Comment by eddef** [comment]
Like this?

**Comment by jtimon** [comment]
Yes, thank you!

**Pull request merged**
