### PR TITLE
Staging: cosmetic changes

### PR DESCRIPTION
**Pull request by r000n**
It will looks so:
Screenshot from 2012-12-20 23:26:30

### CODE REVIEW

**Comment by maaku** [comment]
Overall good, but NAK on the the full-width header. It's a responsive layout and on smaller screens it reads better to have the header, text, and then the download button. I cherry-picked out a revision of that change.

Cosmetically it would be better to have the download button vertically centered. If I can manage the time I'll try to find a clean, cross-platform way to do that.

**Comment by r000n** [comment]
I don't understood about full-width header.
With it download button already looks as vertically centered.
Without - we have big spare space.
Compare two images (width 1005px)

with_full_width_header

without_full_width_header

> header, text, and then the download button

It already exists. Small screen - widow resized to 677px (yes, with full-header :)):

677px

**Comment by r000n** [comment]
Screen resolutions ( http://www.w3schools.com/browsers/browsers_display.asp ):

> Today, most visitors have a screen resolution higher than 1024x768 pixels:
> Higher          85%
> 1024x768    13%
> 800x600         1%
> 640x480         0%
> Other               1%

**Comment by r000n** [comment]
W3Counter has other statistics ( http://www.w3counter.com/globalstats.php ):

> 1    1366x768   19.20%
> 2    1024x768   14.07%
> 3    1280x800   10.63%
> 4    1280x1024   7.08%
> 5    1440x900    5.97%
> 6    1920x1080   5.73%
> 7    320x480     4.65%
> 8    1600x900    3.70%
> 9    768x1024    3.62%
> 10   1680x1050   3.30%

But with 320x480 standard freico.in version not viewed anyway.
For 700px+ modes it better with full-width header

**Comment by r000n** [comment]
I propose to consider screen resolution "for Internet" as 1024+

**Comment by maaku** [comment]
I actually meant mobile browsers (Android, for example). There are cross-platform ways to vertically center content. Now that the release is out I'll take a look at this.

**Comment by r000n** [comment]
Freicoin don't works under Android. Why we should bother about it?

**Comment by r000n** [comment]
Phones:
Samsung Galaxy     800x480
Apple iPhone 5      1136x640
Sony Xperia TX     1280x720
Google Nexus 4     1280x768

Tablets:
Samsung Galaxy Tab   1024x600
Explay Informer 708        800x480
Google Nexus 7             1280x800
Asus Eee Pad                1280x800
Apple iPad 2                  1024x768

**Comment by r000n** [comment]
Primary auditory of site - desktop users under WIndows, Mac and Linux. They have high-resolution displays. And site shall be comfortable for them.

**Pull request merged**
