### PR TITLE
Staging - links to twitter and identi.ca

### PR DESCRIPTION
**Pull request by r000n**
I tried make it "in right way" - with vertical alignment, but unsuccessfully. So, simple and straight way

### CODE REVIEW

**Comment by maaku** [comment]
Hey sorry this didn't get merged in earlier; with the holidays I guess I let it slip under the radar. Since you deleted your branch I had to re-create the pull request, but it should in in now.

**Comment by r000n** [comment]
Something strange here.
How you done it? :)
And by some reason, site not updated.
I pushed staging again.

**Comment by r000n** [comment]
Probably, GitHub awaiting "right merge".
I it so, you need:
- remove last commit locally (git reset HEAD^ --hard)
- force update remote (git push origin HEAD --force)
- and merge pull request directly on GitHub

**Comment by r000n** [comment]
Ok. Buttons are visible

**Pull request closed without merging**
