### PR TITLE
Added bios images, new wiki

### PR DESCRIPTION
**Pull request by joeswhite**
Added images (and twitter handle to jorge timon) to bios pages, also added link to wiki.freicoin.us (new community wiki just started by myself in an attempt to get more knowledge about freicoin out there).

### CODE REVIEW

**Comment by jtimon** [comment]
We already had a wiki ( https://github.com/freicoin/freicoin/wiki ), just not with many articles...

**Comment by joeswhite** [comment]
I figure another wiki can't hurt, I can probably get more people to edit my wiki as I can drum up support from the miners. Also, fixing those commits now. Not the best with github yet so thanks for your patience

**Comment by joeswhite** [comment]
Also, would you like me to link to that wiki as well?

**Comment by jtimon** [comment]
Yes, it will definitely not hurt. If you take the articles from here probably having just one is enough.
Maybe people are more used to wikimedia, I don't know. I was just pointing it out in case you didn't know.

**Comment by joeswhite** [comment]
Sounds good, and I actually did not know there was a wiki already. Also yeah, wikimedia is probably a much more "known" system. Feels a bit more newbie friendly than git's wiki.

**Comment by joeswhite** [comment]
fixed commit issue as noted earlier, I have not yet added the other wiki to the list. Do you want me to move those articles over to my wiki or would you like to?

I believe this pull request should be okay to merge in to the main branch

**Comment by jtimon** [comment]
Although I've merged this could have been a just a couple of commits, one for the updates bios and one for the wiki. Look at the "files changed" tab, you're undoing some of your own changes.
with "git reset HEAD~1" you can cancel the last commit but leave the changes unstaged (you can commit them again, maybe with new changes). That may be a simpler way to unify commits than interactive rebase (although the later is much more powerful).

**Comment by joeswhite** [comment]
Thanks, I honestly prefer to do smaller commits than one big commit but for this project I'll try my best to do that. Still learning the github stuff. thanks for the education

**Comment by jtimon** [comment]
Well, that's my point, in this case they would have been two small commits. The end result is 8 additions and 4 deletions, the history could have been simplified if the formatting fixes where included in the previous commits. Anyway, as said it's not very important for this project, just want to offer some help on git because I know from experience that it takes some time to get used to it.

**Pull request merged**
